include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    unnecessary_lambdas: true
    avoid_renaming_method_parameters: false
    prefer_const_constructors: true

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**.g.dart'

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
formatter:
  trailing_commas: preserve
  page_width: 200
